question_page_hello:
  path: '/questionpage/hello'
  defaults:
    _controller: '\Drupal\training\Controller\TrainingController::showForm'
  requirements:
    _permission: 'view content'

magic_form:
  path: '/magic'
  defaults:
    _form: '\Drupal\training\Form\MagicQuestionForm'
  requirements:
    _permission: 'access content'

settings_form:
  path: '/training/config'
  defaults:
    _form: 'Drupal\training\Form\ConfigForm'
  requirements:
    _permission: 'administer site configuration'